from __future__ import annotations

"""drift_runner.py — parse Atlas reports/state artifacts → list[DriftRecord].

Reads coverage report files already generated by the pipeline, plus selected
platform state artifacts used for alert-plane consolidation.
Does not re-run generators; decoupled from the store loading cycle.

Usage (CLI):
    python tools/drift_runner.py          # print all records
    python tools/drift_runner.py --json   # print JSON array
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.drift import DriftRecord
from tools.store import load_store

_OUTPUT_DIR = Path("/opt/stack/services/docs/kb/Projects/Atlas/40-OUTPUT")
_OUTPUT_FILE_DIR = _OUTPUT_DIR  # same location; orphaned files live here

KB_REPORT = _OUTPUT_DIR / "KB Coverage Report.md"
CATALOG_REPORT = _OUTPUT_DIR / "Catalog Coverage Report.md"
OUTPUT_REPORT = _OUTPUT_DIR / "Output Integrity Report.md"
MONITORING_REPORT = _OUTPUT_DIR / "Monitoring Coverage Report.md"
ATLAS_PROBE_STATE = Path("/opt/stack/services/automations/state/atlas_probe_latest.json")
LEGACY_STAGE3_STATE = Path(
    "/opt/stack/services/projects/operator-kernel/artifacts/stage3/stage3_operations_latest.json"
)


def _table_rows(text: str, section_heading: str) -> list[list[str]]:
    """Extract non-header rows from the markdown table under section_heading."""
    # Find the section
    pattern = re.compile(
        rf"^## {re.escape(section_heading)}.*?(?=^## |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        return []

    section = match.group(0)
    rows: list[list[str]] = []
    in_table = False
    for line in section.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and not stripped.startswith("|---"):
            cells = [c.strip().strip("`") for c in stripped.split("|") if c.strip()]
            if not in_table:
                in_table = True  # first row is header
                continue
            rows.append(cells)
    return rows


def parse_kb_coverage(report_path: Path = KB_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    # Orphan dirs
    for row in _table_rows(text, "Orphan Directories (kb/Projects dir with no atlas-store entity)"):
        if len(row) < 2:
            continue
        dir_name, norm_id = row[0], row[1]
        records.append(DriftRecord(
            kind="kb_orphan_dir",
            entity_type="project",
            id=dir_name,
            normalized_id=norm_id,
            detail=f"kb/Projects directory '{dir_name}' has no atlas-store entity (would be '{norm_id}')",
            fix_tier="propose",
        ))

    # Broken concept_doc refs
    for row in _table_rows(text, "Broken concept_doc References (entity points to missing file)"):
        if len(row) < 2:
            continue
        entity_id, doc_path = row[0], row[1]
        records.append(DriftRecord(
            kind="broken_concept_doc",
            entity_type="project",
            id=entity_id,
            detail=f"Entity '{entity_id}' concept_doc not found on disk: {doc_path}",
            fix_tier="flag",
            extra={"concept_doc": doc_path},
        ))

    return records


def parse_catalog_coverage(report_path: Path = CATALOG_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    for row in _table_rows(text, "Catalog-Only Services (in catalog.json, no atlas-store entity)"):
        if not row:
            continue
        service_key = row[0]
        records.append(DriftRecord(
            kind="catalog_only_service",
            entity_type="service",
            id=service_key,
            detail=f"Service '{service_key}' exists in catalog.json but has no atlas-store entity",
            fix_tier="propose",
        ))

    return records


def parse_output_integrity(report_path: Path = OUTPUT_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    for row in _table_rows(text, "Orphaned Output Files"):
        if not row:
            continue
        filename = row[0]
        records.append(DriftRecord(
            kind="orphaned_output_file",
            entity_type="output_file",
            id=filename,
            detail=f"Output file '{filename}' is not claimed by any generator OUTPUTS[]",
            fix_tier="auto",
            extra={"path": str(_OUTPUT_FILE_DIR / filename)},
        ))

    return records


def parse_monitoring_coverage(report_path: Path = MONITORING_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    for row in _table_rows(text, "Baseline Gaps (missing container_name or systemd_unit)"):
        if len(row) < 3:
            continue
        service_id, stype, missing = row[0], row[1], row[2]
        records.append(DriftRecord(
            kind="monitoring_baseline_gap",
            entity_type="service",
            id=service_id,
            detail=f"Service '{service_id}' ({stype}) missing baseline monitoring: {missing}",
            fix_tier="flag",
            extra={"service_type": stype, "missing": missing},
        ))

    for row in _table_rows(text, "Health Endpoint Gaps (has port, no health_endpoint)"):
        if len(row) < 3:
            continue
        service_id, port, missing = row[0], row[1], row[2]
        records.append(DriftRecord(
            kind="monitoring_health_gap",
            entity_type="service",
            id=service_id,
            detail=f"Service '{service_id}' has port {port} but is missing: {missing}",
            fix_tier="flag",
            extra={"port": port, "missing": missing},
        ))

    # Warn-level dimensions (like resource_budget) are still blocker-relevant for runtime policy.
    for row in _table_rows(text, "Full Coverage Scorecard"):
        if len(row) < 4:
            continue
        service_id, stype, score, gaps = row[0], row[1], row[2], row[3]
        if "resource_budget" not in gaps:
            continue
        records.append(DriftRecord(
            kind="monitoring_resource_budget_gap",
            entity_type="service",
            id=service_id,
            detail=f"Service '{service_id}' ({stype}) is missing resource_budget policy metadata",
            fix_tier="flag",
            extra={"service_type": stype, "score": score, "missing": "resource_budget"},
        ))

    return records


def parse_probe_drift(state_path: Path = ATLAS_PROBE_STATE) -> list[DriftRecord]:
    """Parse cached atlas probe results into flag-tier platform drift records."""
    records: list[DriftRecord] = []
    if not state_path.exists():
        return records

    try:
        payload = json.loads(state_path.read_text(encoding="utf-8"))
    except Exception:
        return records

    for result in payload.get("results", []):
        if not isinstance(result, dict) or not result.get("drift"):
            continue

        service_id = str(result.get("service_id", "")).strip()
        if not service_id:
            continue

        failed_probes: list[str] = []
        for probe in result.get("probes", []):
            if not isinstance(probe, dict):
                continue
            if probe.get("pass") is True:
                continue
            ptype = str(probe.get("type", "unknown")).strip() or "unknown"
            actual = str(probe.get("actual", "")).strip()
            expected = str(probe.get("expected", "")).strip()
            if actual and expected:
                failed_probes.append(f"{ptype}: actual={actual}, expected={expected}")
            elif actual:
                failed_probes.append(f"{ptype}: actual={actual}")
            else:
                failed_probes.append(ptype)

        detail = f"Runtime probe drift for service '{service_id}'"
        if failed_probes:
            detail += f" ({'; '.join(failed_probes[:3])})"

        records.append(
            DriftRecord(
                kind="platform_probe_drift",
                entity_type="service",
                id=service_id,
                detail=detail,
                fix_tier="flag",
                extra={
                    "source": str(state_path),
                    "name": str(result.get("name", service_id)),
                    "lifecycle": str(result.get("lifecycle", "")),
                    "failed_probes": failed_probes,
                },
            )
        )

    return records


def parse_legacy_stage3_alerts(state_path: Path = LEGACY_STAGE3_STATE) -> list[DriftRecord]:
    """Parse legacy Operator Kernel Stage3 failures into flag-tier records.

    This lets Atlas surface pre-retirement legacy alert engine failures through
    the same loop-closure/escalation lane as other drift signals.
    """
    records: list[DriftRecord] = []
    if not state_path.exists():
        return records

    try:
        payload = json.loads(state_path.read_text(encoding="utf-8"))
    except Exception:
        return records

    status = str(payload.get("status", "")).strip().lower()
    alerts = payload.get("alerts", [])
    if not isinstance(alerts, list):
        alerts = []
    alerts = [str(a).strip() for a in alerts if str(a).strip()]

    # Only emit when legacy stage3 currently reports failure-like state.
    if status not in {"fail", "error", "degraded"} and not alerts:
        return records

    detail = "Legacy Stage3 operations engine reports failing state"
    if alerts:
        detail += f" ({'; '.join(alerts[:3])})"

    records.append(
        DriftRecord(
            kind="legacy_stage3_alert",
            entity_type="service",
            id="operator-kernel-stage3-ops",
            detail=detail,
            fix_tier="flag",
            extra={
                "source": str(state_path),
                "status": status,
                "alerts": alerts,
                "webhook_status": str(payload.get("webhook_status", "")),
                "generated_at": str(payload.get("generated_at", "")),
                "alert_artifacts": payload.get("alert_artifacts", {}),
            },
        )
    )

    return records


def parse_task_coverage() -> list[DriftRecord]:
    """Emit task tracking drift for active/in_progress projects.

    Rule intent:
    - active/in_progress projects should have a current next_action
    - active/in_progress projects should have at least one canonical open task
    """
    records: list[DriftRecord] = []
    try:
        store = load_store(REPO_ROOT)
    except Exception:
        return records

    projects = store.get("project", {})
    tasks = store.get("task", {})

    open_states = {"open", "in_progress", "blocked"}
    open_task_count: dict[str, int] = {}
    for model in tasks.values():
        status = getattr(model, "status", "")
        if status not in open_states:
            continue
        project_id = getattr(model, "project_id", "")
        if not project_id:
            continue
        open_task_count[project_id] = open_task_count.get(project_id, 0) + 1

    for project_id, model in projects.items():
        status_ref = getattr(model, "status", None)
        status = getattr(status_ref, "value_id", "")
        if status not in {"active", "in_progress"}:
            continue

        next_action = str(getattr(model, "next_action", "") or "").strip()
        open_count = int(open_task_count.get(project_id, 0))

        if not next_action and open_count == 0:
            records.append(
                DriftRecord(
                    kind="task_tracking_gap",
                    entity_type="project",
                    id=project_id,
                    detail=(
                        f"Project '{project_id}' is {status} but has neither next_action nor open canonical tasks"
                    ),
                    fix_tier="flag",
                    extra={"status": status, "open_task_count": open_count},
                )
            )
            continue

        if not next_action:
            records.append(
                DriftRecord(
                    kind="task_missing_next_action",
                    entity_type="project",
                    id=project_id,
                    detail=f"Project '{project_id}' is {status} but next_action is empty",
                    fix_tier="flag",
                    extra={"status": status, "open_task_count": open_count},
                )
            )

        if open_count == 0:
            records.append(
                DriftRecord(
                    kind="task_missing_open_work",
                    entity_type="project",
                    id=project_id,
                    detail=f"Project '{project_id}' is {status} but has no open canonical tasks",
                    fix_tier="flag",
                    extra={"status": status},
                )
            )

    return records


def collect_all() -> list[DriftRecord]:
    return (
        parse_kb_coverage()
        + parse_catalog_coverage()
        + parse_output_integrity()
        + parse_monitoring_coverage()
        + parse_probe_drift()
        + parse_legacy_stage3_alerts()
        + parse_task_coverage()
    )


if __name__ == "__main__":
    records = collect_all()
    if "--json" in sys.argv:
        import dataclasses
        print(json.dumps([dataclasses.asdict(r) for r in records], indent=2))
    else:
        if not records:
            print("No drift detected.")
        for r in records:
            print(r)
        print(f"\nTotal: {len(records)} drift records")
        by_tier = {"auto": 0, "propose": 0, "flag": 0}
        for r in records:
            by_tier[r.fix_tier] += 1
        print(f"  auto={by_tier['auto']}  propose={by_tier['propose']}  flag={by_tier['flag']}")
