from __future__ import annotations

"""drift_runner.py — parse coverage report markdown files → list[DriftRecord].

Reads the three coverage report files already generated by the pipeline.
Does not re-run generators; decoupled from the store loading cycle.

Usage (CLI):
    python tools/drift_runner.py          # print all records
    python tools/drift_runner.py --json   # print JSON array
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.drift import DriftRecord

_OUTPUT_DIR = Path("/opt/stack/services/docs/kb/Projects/Atlas/40-OUTPUT")
_OUTPUT_FILE_DIR = _OUTPUT_DIR  # same location; orphaned files live here

KB_REPORT = _OUTPUT_DIR / "KB Coverage Report.md"
CATALOG_REPORT = _OUTPUT_DIR / "Catalog Coverage Report.md"
OUTPUT_REPORT = _OUTPUT_DIR / "Output Integrity Report.md"


def _table_rows(text: str, section_heading: str) -> list[list[str]]:
    """Extract non-header rows from the markdown table under section_heading."""
    # Find the section
    pattern = re.compile(
        rf"^## {re.escape(section_heading)}\b.*?(?=^## |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        return []

    section = match.group(0)
    rows: list[list[str]] = []
    in_table = False
    for line in section.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and not stripped.startswith("|---"):
            cells = [c.strip().strip("`") for c in stripped.split("|") if c.strip()]
            if not in_table:
                in_table = True  # first row is header
                continue
            rows.append(cells)
    return rows


def parse_kb_coverage(report_path: Path = KB_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    # Orphan dirs
    for row in _table_rows(text, "Orphan Directories (kb/Projects dir with no atlas-store entity)"):
        if len(row) < 2:
            continue
        dir_name, norm_id = row[0], row[1]
        records.append(DriftRecord(
            kind="kb_orphan_dir",
            entity_type="project",
            id=dir_name,
            normalized_id=norm_id,
            detail=f"kb/Projects directory '{dir_name}' has no atlas-store entity (would be '{norm_id}')",
            fix_tier="propose",
        ))

    # Broken concept_doc refs
    for row in _table_rows(text, "Broken concept_doc References (entity points to missing file)"):
        if len(row) < 2:
            continue
        entity_id, doc_path = row[0], row[1]
        records.append(DriftRecord(
            kind="broken_concept_doc",
            entity_type="project",
            id=entity_id,
            detail=f"Entity '{entity_id}' concept_doc not found on disk: {doc_path}",
            fix_tier="flag",
            extra={"concept_doc": doc_path},
        ))

    return records


def parse_catalog_coverage(report_path: Path = CATALOG_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    for row in _table_rows(text, "Catalog-Only Services (in catalog.json, no atlas-store entity)"):
        if not row:
            continue
        service_key = row[0]
        records.append(DriftRecord(
            kind="catalog_only_service",
            entity_type="service",
            id=service_key,
            detail=f"Service '{service_key}' exists in catalog.json but has no atlas-store entity",
            fix_tier="propose",
        ))

    return records


def parse_output_integrity(report_path: Path = OUTPUT_REPORT) -> list[DriftRecord]:
    records: list[DriftRecord] = []
    if not report_path.exists():
        return records

    text = report_path.read_text(encoding="utf-8")

    for row in _table_rows(text, "Orphaned Output Files"):
        if not row:
            continue
        filename = row[0]
        records.append(DriftRecord(
            kind="orphaned_output_file",
            entity_type="output_file",
            id=filename,
            detail=f"Output file '{filename}' is not claimed by any generator OUTPUTS[]",
            fix_tier="auto",
            extra={"path": str(_OUTPUT_FILE_DIR / filename)},
        ))

    return records


def collect_all() -> list[DriftRecord]:
    return (
        parse_kb_coverage()
        + parse_catalog_coverage()
        + parse_output_integrity()
    )


if __name__ == "__main__":
    records = collect_all()
    if "--json" in sys.argv:
        import dataclasses
        print(json.dumps([dataclasses.asdict(r) for r in records], indent=2))
    else:
        if not records:
            print("No drift detected.")
        for r in records:
            print(r)
        print(f"\nTotal: {len(records)} drift records")
        by_tier = {"auto": 0, "propose": 0, "flag": 0}
        for r in records:
            by_tier[r.fix_tier] += 1
        print(f"  auto={by_tier['auto']}  propose={by_tier['propose']}  flag={by_tier['flag']}")
